### PR TITLE
Fix NVIDIA driver version in the dockerfile

### PR DESCRIPTION
**Pull request by xuzhao9**
This PR also removes the requirement of copying NVIDIA driver files to /lib/x86_64-linux-gnu.

However, it pins the NVIDIA driver version to 525.60.13. When we update infra, we need to update the NVIDIA driver version in the docker file too.

Test Plan:
Optim Benchmark
https://github.com/pytorch/benchmark/actions/runs/4634904570

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
test plan?

stamp to unblock, but did you launch a run on the a100s

**Comment by xuzhao9** [comment]
> test plan?
> 
> stamp to unblock, but did you launch a run on the a100s

Let's run an example optim benchmark tomorrow to test the new workflow.

**Comment by janeyx99** [comment]
haha the optim benchmark will run in 1.5hours

**Comment by xuzhao9** [comment]
> haha the optim benchmark will run in 1.5hours

Added a new optim benchmark as the Test Plan, but I am pretty sure this will work.

**Comment by janeyx99** [comment]
yea go for it

**Pull request closed without merging**
