### PR TITLE
Port pytorch/benchmarks/dynamo to the dynamo userbenchmark

### PR DESCRIPTION
**Pull request by xuzhao9**
Copy the code from https://github.com/pytorch/pytorch/tree/main/benchmarks/dynamo to make it as a torchbench userbenchmark.
Need to refactor the code to work on pytorch nightly release.

Test plan:

```
$ python run_benchmark.py dynamo --performance --only resnet50 --training
WARNING:userbenchmark.dynamo.common:torch.cuda.is_available() == False, using CPU
loading model: 0it [00:18, ?it/s]
cpu  train resnet50
 15/ 16 +1 frames  -2s 12 graphs  3 graph calls  231/ 581 =  40% ops  32% time
```

```
$ python run_benchmark.py dynamo --performance --only resnet50 --training
loading model: 0it [00:06, ?it/s]
cuda train resnet50
 22/ 22 +0 frames   2s  4 graphs  4 graph calls  233/ 586 =  40% ops  51% time
```

### CODE REVIEW

**Comment by FindHao** [comment]
For now, it only works with `--only model_name`, right? How can we run all models with this userbenchmark?

**Comment by xuzhao9** [comment]
> 

Yes, it could iterate through all models, just remove the `--only` argument.

**Review by FindHao — APPROVED** [review]
Only serveral models failed the testing for training. Here is the log. [run_log.txt](https://github.com/pytorch/benchmark/files/12363845/run_log.txt)
LGTM!

**Comment by xuzhao9** [comment]
It is fine, we can fix them when dynamo team is really using this.

**Pull request closed without merging**
