### PR TITLE
add graph freezing and weight prepacking argument

### PR DESCRIPTION
**Pull request by snadampal**
set the following argument to freeze the graph and enable weights prepacking during torch.compile with inductor compiler

"--freeze_prepack_weights"

### CODE REVIEW

**Review by xuzhao9 — APPROVED** [review]

**Comment by xuzhao9** [comment]
LGTM!

**Comment by xuzhao9** [comment]
@snadampal We recently refactored the code related to setting up inductor config options, can you help migrate to the new style of the options, thanks!

**Comment by snadampal** [comment]
sure @xuzhao9 , i will rebase once the other PR is merged.

**Comment by xuzhao9** [comment]
@snadampal Just a ping that the PR has been merged and we can update this PR now. Thanks!

**Comment by snadampal** [comment]
Thanks for the note, I will rebase.

**Comment by snadampal** [comment]
hi @xuzhao9 , i have rebased it now. please review.

**Pull request closed without merging**
