### PR TITLE
[backends] Fix Torch-TRT backend and userbenchmark

### PR DESCRIPTION
**Pull request by gs-olive**
- Improve error checking in benchmark
- Improve argument handling and processing in backend

### CODE REVIEW

**Review by xuzhao9 — APPROVED** [review]
LGTM, I am also looking into the Background_Matting model on the `set_module()` issue.

**Comment by xuzhao9** [comment]
Test workflow run: https://github.com/pytorch/benchmark/actions/runs/6409029498

**Comment by gs-olive** [comment]
@xuzhao9 - Thanks for running this! It looks like it worked! I am wondering where I could find TorchBench results times for Inductor or PyTorch Eager for comparison?

**Comment by gs-olive** [comment]
Thanks for sharing - this is very helpful. I am wondering if you know, for performance speedup/absolute execution time in the Inductor HUD, as well as the reported times in the `eager` csv, like this: `"test_eval[vision_maskrcnn-cuda-eager]_cmem": 0.9033203125,`, what batch size or precisions are being used, or where would I find the code that controls this? I am trying to better understand how to compare the metrics and I want to make sure it is a fair comparison

**Comment by xuzhao9** [comment]
@gs-olive The code controlled to generate the Inductor HUD is located at https://github.com/pytorch/pytorch/blob/main/benchmarks/dynamo/torchbench.py and https://github.com/pytorch/pytorch/blob/71beca4899dbe1e9b53f8451b8e33fb816465dcc/.ci/pytorch/test.sh#L494

**Pull request closed without merging**
