### PR TITLE
Improve DLRM utilization on CUDA

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Increase the complexity of the DLRM benchmark to improve
the utilization on GPU. DLRM's structure needs to be more complex
for the random inputs to be larger, this improves the profile
collected on the benchmark, and matches closer to real world
examples.

## Traces Collected

Here is the trace collected before any modifications on A100:
image

Here is the eval trace collected using settings described in the paper on A100:
```
--arch-embedding-size=1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-sparse-feature-size=64 --arch-mlp-bot=512-512-64 --arch-mlp-top=1024-1024-1024-1 --mini-batch-size=2048 --num-batches=1000 --num-indices-per-lookup=100
```
image

Here is the eval trace upon further tweaking the complexity beyond the paper on A100:
```
--arch-embedding-size=1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --arch-sparse-feature-size=128 --arch-mlp-bot=1024-1024-1024-1024-128 --arch-mlp-top=2048-2048-2048-2048-2048-2048-2048-1 --mini-batch-size=2048 --num-batches=1000 --num-indices-per-lookup=100
```
image

Same arguments on Tesla T4:
image

Note: the DLRM forward pass splits into several sections in the image:
- Bottom MLP (dense features - green)
- EmbeddingBag (sparse features - blue)
- Interact Features (both dense and sparse - too small to see)
- Top MLP (probability of a click - green)

## Idleness Evaluation
To increase utilization of the DLRM model, it is not a batch size search, but instead a model structural search. Increasing the model complexity will increase the GPU utilization, since the random data loader is dependent on the model. Therefore, the more layers and features in each bottom, embedding and top models, the better the GPU utilization.

### CODE REVIEW

**Comment by xuzhao9** [comment]
Can we also get the stability result? For example, try running the benchmark for 10 times and see if the latency results are stable enough? I still expect the result difference (max - min / min) to be < 10% even when the environment is not tuned.

**Comment by aaronenyeshi** [comment]
I ran it 15 times, and it doesn't look very stable on the T4. See the results below, and the last row is the (max-min)/min, which is much bigger than 10%.
Run | GPU Time (ms) | CPU Dispatch Time (ms) | CPU Total Time (ms)
-- | -- | -- | --
1 | 49.680 | 15.002 | 49.680
2 | 39.220 | 13.688 | 39.220
3 | 48.096 | 14.942 | 48.117
4 | 52.253 | 16.320 | 52.263
5 | 53.099 | 16.414 | 53.102
6 | 39.769 | 13.603 | 39.773
7 | 48.768 | 14.841 | 48.773
8 | 38.971 | 13.442 | 38.972
9 | 39.662 | 14.844 | 39.669
10 | 39.463 | 13.263 | 39.469
11 | 43.894 | 16.134 | 43.902
12 | 39.618 | 13.473 | 39.623
13 | 39.020 | 13.390 | 39.022
14 | 44.363 | 14.264 | 44.366
15 | 52.892 | 16.031 | 52.895
(max-min)/min | 0.36252598 | 0.23757823 | 0.362568

**Comment by aaronenyeshi** [comment]
After forcing the GPU into persistent mode, and setting the GPU clock and memory frequencies, the results are much more stable (except the first run):

Run | GPU Time (ms) | CPU Dispatch Time (ms) | CPU Total Time (ms)
-- | -- | -- | --
1 | 93.411 | 32.887 | 94.874
2 | 40.286 | 13.447 | 40.291
3 | 40.340 | 13.597 | 40.349
4 | 40.363 | 13.677 | 40.368
5 | 40.325 | 13.555 | 40.330
6 | 40.339 | 13.530 | 40.346
7 | 40.277 | 13.472 | 40.285
8 | 40.279 | 13.448 | 40.282
9 | 40.350 | 13.551 | 40.353
10 | 40.311 | 13.518 | 40.315
11 | 40.321 | 13.511 | 40.325
12 | 40.319 | 13.646 | 40.332
13 | 40.275 | 13.557 | 40.278
14 | 40.290 | 13.417 | 40.304
15 | 40.327 | 13.648 | 40.334

**Review by xuzhao9 — APPROVED** [review]
LGTM. Thanks for improving DLRM!

**Pull request closed without merging**
