### PR TITLE
Add RoBERTa to the model suite

### PR DESCRIPTION
**Pull request by Rohanjames1997**
https://huggingface.co/FacebookAI/xlm-roberta-base

### CODE REVIEW

**Comment by xuzhao9** [comment]
The PR looks good. Do you mind to rebase on the latest main branch and push again?

**Comment by Rohanjames1997** [comment]
Thanks for the review @xuzhao9 ! I've rebased it.

**Review by xuzhao9 — APPROVED** [review]

**Comment by Rohanjames1997** [comment]
@xuzhao9 can you merge it too? I'm not authorized, it seems.

**Comment by xuzhao9** [comment]
@Rohanjames1997 The PR has landed. Thanks for your contribution!

**Pull request closed without merging**
