### PR TITLE
Enhance cpu userbenchmark deal with failures and timeout

### PR DESCRIPTION
**Pull request by chuanqi129**
Fix cpu userbenchmark issue for not implemented models, and add timeout parameter for cpu userbenchmark
It also works for roadmap #1293 

For example:
```shell
$ python run_benchmark.py cpu -m resnet50,Background_Matting,resnet18 --timeout 10
Running benchmark: ['/localdisk/chuanqiw/miniconda3/envs/torchdynamo/bin/python', '/localdisk/chuanqiw/PT/benchmark/userbenchmark/cpu/run_config.py', '-m', 'resnet50', '--device', 'cpu', '-t', 'eval', '-o', '/localdisk/chuanqiw/PT/benchmark/.userbenchmark/cpu/cpu-20230508013240']
Command '['/localdisk/chuanqiw/miniconda3/envs/torchdynamo/bin/python', '/localdisk/chuanqiw/PT/benchmark/userbenchmark/cpu/run_config.py', '-m', 'resnet50', '--device', 'cpu', '-t', 'eval', '-o', '/localdisk/chuanqiw/PT/benchmark/.userbenchmark/cpu/cpu-20230508013240']' timed out after 10 seconds
Running benchmark: ['/localdisk/chuanqiw/miniconda3/envs/torchdynamo/bin/python', '/localdisk/chuanqiw/PT/benchmark/userbenchmark/cpu/run_config.py', '-m', 'Background_Matting', '--device', 'cpu', '-t', 'eval', '-o', '/localdisk/chuanqiw/PT/benchmark/.userbenchmark/cpu/cpu-20230508013240']
Running TorchBenchModelConfig(name='Background_Matting', device='cpu', test='eval', batch_size=None, jit=False, extra_args=[], extra_env=None) ... [NotImplemented]

Running benchmark: ['/localdisk/chuanqiw/miniconda3/envs/torchdynamo/bin/python', '/localdisk/chuanqiw/PT/benchmark/userbenchmark/cpu/run_config.py', '-m', 'resnet18', '--device', 'cpu', '-t', 'eval', '-o', '/localdisk/chuanqiw/PT/benchmark/.userbenchmark/cpu/cpu-20230508013240']
Running TorchBenchModelConfig(name='resnet18', device='cpu', test='eval', batch_size=None, jit=False, extra_args=[], extra_env=None) ... [Done]
```

### CODE REVIEW

**Comment by chuanqi129** [comment]
Hi @xuzhao9 , I have tried to trigger the cpu userbenchmark test on T4 metal in https://github.com/pytorch/benchmark/actions/runs/4942883136, but it crashed on pytorch nightly installation. Could you please help to double check it?

**Comment by xuzhao9** [comment]
@chuanqi129 The reason is because the torchaudio/torchvision nightly release is broken, we are working on torchbench docker to mitigate this. Working on it.

**Comment by xuzhao9** [comment]
@chuanqi129 The reason is because the torchaudio/torchvision nightly release is broken, we are working on migrating the workflow to torchbench docker to mitigate this. Working on it.

**Comment by xuzhao9** [comment]
@chuanqi129 Can you help rebase on the latest main branch, and rerun the "cpu" userbenchmark on your branch with this workflow? https://github.com/pytorch/benchmark/actions/workflows/userbenchmark-c5-24xlarge.yml Thanks!

**Comment by chuanqi129** [comment]
> @chuanqi129 Can you help rebase on the latest main branch, and rerun the "cpu" userbenchmark on your branch with this workflow? https://github.com/pytorch/benchmark/actions/workflows/userbenchmark-c5-24xlarge.yml Thanks!

Rebased and triggered the workflow in https://github.com/pytorch/benchmark/actions/runs/4954275955

**Comment by xuzhao9** [comment]
Fixed a bug in the workflow file, running it again: https://github.com/pytorch/benchmark/actions/runs/4954822650

**Comment by chuanqi129** [comment]
> Fixed a bug in the workflow file, running it again: https://github.com/pytorch/benchmark/actions/runs/4954822650

Updated a typo and rerun the https://github.com/pytorch/benchmark/actions/runs/4954822650

**Comment by xuzhao9** [comment]
Applied other fixes and running https://github.com/pytorch/benchmark/actions/runs/4959518570

**Comment by chuanqi129** [comment]
Suggest to trigger the cpu userbenchmark workflow test with `--launcher --launcher-args \"--node-id 0\"`, it will bind cores and set OMP thread and other env vars. May help to get more stable performance. cc @xuzhao9

**Comment by xuzhao9** [comment]
@chuanqi129 Currently we are only testing the workflow, so it is fine that we don't get stable results.

**Comment by chuanqi129** [comment]
> @chuanqi129 Currently we are only testing the workflow, so it is fine that we don't get stable results.

Sounds good to me 😃

**Pull request closed without merging**
