### PR TITLE
Add fsdp to e2e hf_bert

### PR DESCRIPTION
**Pull request by erichan1**
Basically the same as https://github.com/pytorch/benchmark/pull/1142

### CODE REVIEW

**Comment by erichan1** [comment]
`import torchtext` failure still seems to be main cause of benchmark run failure. Do not believe it's relevant to this change.

**Comment by xuzhao9** [comment]
Right, it seems recent torchtext nightly is broken for some reasons. This should be irrelevant.

**Review by xuzhao9 — APPROVED** [review]
LGTM, thanks!

**Comment by erichan1** [comment]
Run command: 
```
python run_benchmark.py distributed --ngpus 8 --nodes 1  --model torchbenchmark.e2e_models.hf_bert.Model --trainer torchbenchmark.util.distributed.trainer.Trainer --distributed ddp --job_dir $PWD/.userbenchmark/distributed/e2e_hf_bert
```
Metrics output: 
```
placeholder
```

**Pull request closed without merging**
