### PR TITLE
hf and multimodal clip

### PR DESCRIPTION
**Pull request by msaroufim**
multimodal clip is in canary because of torchtext dependency so this adds the hf version

Notably this PR also makes it possible to support dict based inputs to `get_module()` which is very common in HF code

### CODE REVIEW

**Review by eellison — APPROVED** [review]
🚀

**Review by xuzhao9 — APPROVED** [review]
LGTM!

**Comment by msaroufim** [comment]
No space left on device seems like another upstream issue

**Comment by msaroufim** [comment]
Ok I think the problem is `example_inputs` is a dict instead of a list so will need to unpack it correctly in the torchbench tests

**Pull request closed without merging**
