### PR TITLE
Move GNN models to canary_models to bypass CI check

### PR DESCRIPTION
**Pull request by yanbing-j**
Fix https://github.com/pytorch/benchmark/issues/1552.

At current phase, PyTorch nightly does not match dependency libraries from https://data.pyg.org/whl/torch-2.0.0+cu117.html. PyG maintainer has confirmed this, and will not update the wheel based on PyTorch nightly. In this PR, we will move GNN models to `canary_models` to bypass CI check.

Once the wheel in PyG is stable with PyTorch nightly, we will move back to `models`.

### CODE REVIEW

**Review by xuzhao9 — APPROVED** [review]
Thanks for addressing this issue!

**Comment by ezyang** [comment]
@yanbing-j I want to inform you that I plan to redo the GNN models from scratch using the setup from pytorch_geometric/test/nn/models/test_basic_gnn.py which does NOT require any compiled C++ libraries.

**Comment by yanbing-j** [comment]
> @yanbing-j I want to inform you that I plan to redo the GNN models from scratch using the setup from pytorch_geometric/test/nn/models/test_basic_gnn.py which does NOT require any compiled C++ libraries.

Hi @ezyang , I suppose using `test_basic_gnn.py` still needs compiled C++ libraries.

For now, pytorch_geometric depends on `pytorch_scatter` and `pytorch_sparse`, or `pyg-lib`. These libraries has pre-built wheels, which are based on PyTorch 2.0 release. In TorchBench scenarios, they need to be re-built on PyTorch nightly. And PyG maintainer has confirmed this, and will not update the wheel based on PyTorch nightly.

**Comment by ezyang** [comment]
quoting @puririshi98

> as of rn torch-* dependencies are being dropped such that torch+pyg(torch-geometric)+pyg-lib is all you should need. any remaining dependencies on torch-sparse/scatter/etc are being moved to torch native usage or pyg-lib. the benchmark i shared should work with just pytorch+pyg-lib+torch-geometric, if not plz lmk the issues you are seeing and we will address them as top priorities. thanks for adding the benchmark, i am happy to help in any way possible to make the process easy for you

**Comment by yanbing-j** [comment]
I have verified that, in the combination of pytorch nightly + pyg-lib (wheel) + torch-geometric (wheel), `test_basic_gnn.py` has the following error:

  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
Traceback (most recent call last):
  File "/home_local/yanbingj/project/pyg/pytorch_geometric/test/nn/models/test_basic_gnn.py", line 15, in <module>
    from torch_geometric.testing import (
ImportError: cannot import name 'onlyNeighborSampler' from 'torch_geometric.testing' (/home_local/yanbingj/Software/anaconda3/envs/pyg-dev/lib/python3.9/site-packages/torch_geometric/testing/__init__.py)

My test env is:
torch                       2.1.0.dev20230509+cpu
torch-geometric             2.3.1 (pip install torch_geometric)
pyg-lib                     0.2.0+pt20cpu (pip install pyg_lib -f https://data.pyg.org/whl/torch-2.0.0+cpu.html)

**Comment by yanbing-j** [comment]
I have verified that, in the combination of pytorch nightly + pyg-lib (wheel) + torch-geometric (wheel), test_basic_gnn.py has the following error:

  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
Traceback (most recent call last):
  File "/home_local/yanbingj/project/pyg/pytorch_geometric/test/nn/models/test_basic_gnn.py", line 15, in <module>
    from torch_geometric.testing import (
ImportError: cannot import name 'onlyNeighborSampler' from 'torch_geometric.testing' (/home_local/yanbingj/Software/anaconda3/envs/pyg-dev/lib/python3.9/site-packages/torch_geometric/testing/__init__.py)
My test env is:
```
torch                       2.1.0.dev20230509+cpu
torch-geometric             2.3.1 (pip install torch_geometric)
pyg-lib                     0.2.0.dev20230510+pt20cpu (pip install pyg-lib -f https://data.pyg.org/whl/nightly/torch-2.0.0+cpu.html)
```

If I install torch-geometric using `pip install pyg-nightly`, it will get other errors.
`pyg-nightly                 2.4.0.dev20230510`

  File "/home_local/yanbingj/Software/anaconda3/envs/pyg-dev/lib/python3.9/site-packages/pyg_lib/__init__.py", line 38, in <module>
    load_library('libpyg')
  File "/home_local/yanbingj/Software/anaconda3/envs/pyg-dev/lib/python3.9/site-packages/pyg_lib/__init__.py", line 35, in load_library
    torch.ops.load_library(spec.origin)
  File "/home_local/yanbingj/Software/anaconda3/envs/pyg-dev/lib/python3.9/site-packages/torch/_ops.py", line 787, in load_library
    ctypes.CDLL(path)
  File "/home_local/yanbingj/Software/anaconda3/envs/pyg-dev/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home_local/yanbingj/Software/anaconda3/envs/pyg-dev/lib/python3.9/site-packages/libpyg.so: undefined symbol: _ZNK3c106SymInt13toSymNodeImplEv

**Comment by ezyang** [comment]
I think you have to use pytorch_geometric main. With this env:

```
$ pip list | grep -E '(geom|pyg|sparse|scatter)'
pygame                  2.1.2
torch_geometric         2.4.0              /data/users/ezyang/d/pytorch_geometric
```

I can run the test file without any errors.

**Comment by ezyang** [comment]
https://github.com/pytorch/benchmark/pull/1633

**Pull request closed without merging**
