### PR TITLE
changed to proper Xavier initialization, existing implementation was …

### PR DESCRIPTION
**Pull request by eknag**
…resulting in a large negative bias, which was killing all gradients through the following relu. https://paperswithcode.com/method/xavier-initialization

### CODE REVIEW

**Comment by eknag** [comment]
Behavior before 

```
 python run.py dlrm -d cuda -t train
Running train method from dlrm on cuda in eager mode with input batch size 2048 and precision fp32.
gen: tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], device='cuda:0', grad_fn=<ReluBackward0>)
loss: 0.3434426486492157
derivative with respect to first linear layer: tensor([[0., 0., 0.,  ..., 0., 0., 0.],
```

**Comment by eknag** [comment]
Behavior after fix: 

```
➜  benchmark git:(dev/eknag/fix_dlrm_bias_initialization) ✗ python run.py dlrm -d cuda -t train              
Running train method from dlrm on cuda in eager mode with input batch size 2048 and precision fp32.
gen: tensor([[0.0000],
        [0.0000],
        [0.0213],
        ...,
        [0.0000],
        [0.0231],
        [0.0000]], device='cuda:0', grad_fn=<ReluBackward0>)
loss: 0.3336436152458191
derivative with respect to first linear layer: tensor([[ 7.9563e-04,  7.3723e-04,  7.9948e-04,  ...,  7.8230e-04,
```

**Comment by xuzhao9** [comment]
@eknag Thanks for looking into this. The code is from upstream model: https://github.com/facebookresearch/dlrm/blob/main/dlrm_s_pytorch.py#L212

Could you please submit a PR for the facebookresearch/dlrm repository and see what is the feedback there? Thanks!

**Comment by eknag** [comment]
See https://github.com/facebookresearch/dlrm/pull/358

**Review by xuzhao9 — COMMENTED** [review]
@aaronenyeshi Can you also help take a look?

@eknag Could you please also add the URL of the upstream PR (https://github.com/facebookresearch/dlrm/pull/358) to the code? We would like to track all such upstream improvements in the code.

**Comment by eknag** [comment]
@xuzhao9 Added. Let me know if I should do anything else - I'm new to making contributions.

**Review by xuzhao9 — APPROVED** [review]
LGTM

**Pull request closed without merging**
