### PR TITLE
Add GCP A100 bisection workflow

### PR DESCRIPTION
**Pull request by xuzhao9**

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]
Looks great! Awesome to have a bisection flow for gcp a100

**Comment by GuWei007** [comment]
what does GCP mean

**Comment by janeyx99** [comment]
@GuWei007 google cloud provider? platform?

**Comment by xuzhao9** [comment]
@GuWei007  It stands for Google Compute Platform. Our A100 runners are built on top of GCP and K8s.

**Pull request closed without merging**
