### PR TITLE
Enabled running torch.LTC benchmarks using XLA devices

### PR DESCRIPTION
**Pull request by miladm**
Enabled running torch.LTC benchmarks using XLA devices.

I've successfully tested the script on `torchvision` Mask RCNN.

### CODE REVIEW

**Comment by miladm** [comment]
Moved `torch_xla` implementation to a new script. 
@wconstab let me know if this works, or you'd like me to merge it back to `check_lazy.py`

**Comment by wconstab** [comment]
to be honest, we have mostly started using the `lazy_bench.py` script in pytorch repo under lazy_tensor_staging folder.  It has more complexity and focuses on timing rather than just checking simple statistics, but we found over time it's easier to use one script and started adding more statistics/error-message checking into that script.

In short, I am not sure if we care too much about maintaining this script and having a copy is probably fine, up to you.

**Comment by miladm** [comment]
Thanks for the feedback @wconstab!

The idea behind `lazy_bench.py` sounds appealing. Where can I find that script. Didn't find it in this branch at the first glance. Maybe I missed it. lol

**Comment by wconstab** [comment]
@miladm it's here:
https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/lazy_bench.py

**Pull request merged**
