### PR TITLE
Generalise BERT_pytorch's device option

### PR DESCRIPTION
**Pull request by HMellor**
Generalises the interface to the `BERT_pytorch` model so that you can use arbitrary devices, not just CPU or CUDA.

### CODE REVIEW

**Review by xuzhao9 — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by xuzhao9** [comment]
Just curious, what kind of device are you planning to test other than CPU or CUDA?

**Comment by HMellor** [comment]
We're planning on running TorchBench on Graphcore IPUs

**Comment by xuzhao9** [comment]
Awesome! Looking forward to the coverage and performance results.

**Pull request closed without merging**
