### PR TITLE
Adding the model input iterators.

### PR DESCRIPTION
**Pull request by xuzhao9**
This PR adds a new interface, `gen_inputs(self) -> Tuple[Generator, Optional[int]]`. The first element is an iterator of the input data, and the second element is the size of the iterator. If the iterator is infinite, the second value is set to None.

Currently, only implement this on `timm` and `torchvision` models. Both of them use randomly generated inputs, therefore the second value is set to None in both cases.

### CODE REVIEW

**Comment by shunting314** [comment]
The interface I feel more convenient is:
```
get_inputs(self, n_needed: int) -> List[ExampleBatch]
```

When I test the model for n iterations, I'll call get_inputs(self, n) to get n batches and feed each batch to each run.

But I think the interface you provided is also fine, since I can wrap around it.

**Comment by shunting314** [comment]
Do we know what are the list of models that this interface can be implemented?

**Review by shunting314 — APPROVED** [review]

**Comment by xuzhao9** [comment]
> Do we know what are the list of models that this interface can be implemented?

I believe they can be implemented for all models in https://github.com/pytorch/benchmark/tree/main/torchbenchmark/models, but some of them reads data from a mini-dataset, so the length of inputs is limited (for example, `n` will be 10 or something since we don't have more batches).
For others (notably torchvision/timm/huggingface), since the input is randomly generated, we can generate infinite number of inputs

**Comment by shunting314** [comment]
Got it. What's the plan to implement this method for other models in torchbench?

**Comment by xuzhao9** [comment]
> Got it. What's the plan to implement this method for other models in torchbench?

It will need some time to implement, I expect to reach 100% coverage by the end of April

**Pull request closed without merging**
