### PR TITLE
Switch userbenchmar-a100 and v3-bisection to linux.aws.a100

### PR DESCRIPTION
**Pull request by huydhn**
Per @atalman comment in https://github.com/pytorch/pytorch/issues/143215#issuecomment-2546253999

### CODE REVIEW

**Comment by xuzhao9** [comment]
We also need to remove `Tune Nvidia GPU` step as they are not applicable on AWS A100 runner

**Comment by huydhn** [comment]
> We also need to remove `Tune Nvidia GPU` step as they are not applicable on AWS A100 runner. Do we want to include it in this PR, or do it in a follow-up PR?

Oh, I see. I could do it here I guess, it looks simple enough

**Review by atalman — APPROVED** [review]
lgtm, lets see if it passes

**Review by xuzhao9 — APPROVED** [review]

**Comment by xuzhao9** [comment]
LGTM

**Pull request closed without merging**
