### PR TITLE
Remove niter for models

### PR DESCRIPTION
**Pull request by xuzhao9**
We should remove niter and use the runner to control number of iterations.
Fixes https://github.com/pytorch/benchmark/issues/1023

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
Stamping as the code looks correct to me and I've also wanted to make this change previously.

however, please don't merge until you talk to @jansel and @Krovatkin, anyone else who might be using torchbench and depending on niter arg.  I don't know of anyone actually using it, but it'd be bad to just make it disappear under someone.

**Comment by jansel** [comment]
> Stamping as the code looks correct to me and I've also wanted to make this change previously.
> 
> however, please don't merge until you talk to @jansel and @Krovatkin, anyone else who might be using torchbench and depending on niter arg. I don't know of anyone actually using it, but it'd be bad to just make it disappear under someone.

This is fine.  TorchDynamo only uses the `get_module()` API since it is more flexible. 

Could we rewrite `train()`/`eval()` to just use the `get_module()` API?  That might make torchbecnh easier to maintain.

**Comment by xuzhao9** [comment]
@jansel I would still prefer to keep `train()` and `eval()` as-is, because model code can be very diverse, and I feel `get_module()` is over-simplifying the actual train/eval loops. For example, some models we would like to run more than 1 batch of data (like [fastNLP]()), some requires more than one `torch.nn.Module` to run an entire train/eval loop (like [soft_actor_critic](https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/soft_actor_critic/__init__.py#L199=), [dcgan](https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/dcgan/__init__.py#L223=))

**Comment by jansel** [comment]
> @jansel I would still prefer to keep `train()` and `eval()` as-is, because model code can be very diverse, and I feel `get_module()` is over-simplifying the actual train/eval loops. For example, some models we would like to run more than 1 batch of data (like [fastNLP](https://github.com/pytorch/torchdynamo/issues/165#issuecomment-1113496749)), some requires more than one `torch.nn.Module` to run an entire train/eval loop (like [soft_actor_critic](https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/soft_actor_critic/__init__.py#L199=), [dcgan](https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/dcgan/__init__.py#L223=))

Could we just do something custom for the few models that do weird stuff, then use a generic loop for most other models?

**Comment by xuzhao9** [comment]
@jansel  Sure, I can implement a general version of `train()` and  `eval()` using `get_module()` in the base model.

**Pull request closed without merging**
