### PR TITLE
Use CUDA 11.8 versions as the default

### PR DESCRIPTION
**Pull request by xuzhao9**
Use CUDA 11.8 as the default as CUDA 11.7 is being deprecated.

### CODE REVIEW

**Comment by xuzhao9** [comment]
qq @atalman: when are we deprecating CUDA 11.7 ?

**Review by spzala — COMMENTED** [review]
@xuzhao9 a small review comment :) -  I think we should update the README (which currently says, `we support CUDA 11.7+, and use CUDA 11.7 as default` ) to change the default to 11.8 as well? https://github.com/pytorch/benchmark#installation Thanks!

**Comment by xuzhao9** [comment]
> @xuzhao9 a small review comment :) - I think we should update the README (which currently says, `we support CUDA 11.7+, and use CUDA 11.7 as default` ) to change the default to 11.8 as well? https://github.com/pytorch/benchmark#installation Thanks!

Addressed - thanks for pointing it out!

**Comment by spzala** [comment]
@xuzhao9 yrw, thank you!

**Pull request closed without merging**
